Empty request body for testnet tokens
Without this fix, using the request_testnet_tokens
function yields the following error for me:

TypeError: _post() missing 1 required positional argument: 'data'